### ISSUE TITLE
这个代码确定不会造成死循环么？

### ISSUE THREAD

**Issue by GitterYang** [LSure/AppPlaceholder#1]
- (void)sure_reloadData {
    [self checkEmpty];
    [self sure_reloadData];
}
这个代码确定不会造成死循环么？而不是
- (void)sure_reloadData {
    [self checkEmpty];
    [self reloadData];
}

**Comment by LSure** [comment]
不会的，sure-reload这时已经被替换成reloaddata了，相反你直接调用reloaddata才真的会死循环，你可以参照我简书写的runtime method swizzling 实例汇总，里面有详细解释。


发自网易邮箱大师
在2016年12月13日 08:58，GitterYang 写道:
(void)sure_reloadData {
[self checkEmpty];
[self sure_reloadData];
}
这个代码确定不会造成死循环么？而不是
(void)sure_reloadData {
[self checkEmpty];
[self reloadData];
}

**Comment by GitterYang** [comment]
恩，涨知识了
