### ISSUE TITLE
对于我不想显示的占位图的tableview，该如何处理呢

### ISSUE THREAD

**Issue by OrageKK** [LSure/AppPlaceholder#4]
当我使用searchBar的时候，跳转的搜索控制器，第一次是没有历史记录的，就会显示占位图，挡住了后边的视图，当有搜索记录的时候，这个问题就没有了。所以我想问可否给一个属性或者方法，指定某些tableview显示或者指定某些tableview不显示

**Comment by LSure** [comment]
这个问题已经修复了，可以下载最新的库文件，已添加了firstReload属性加以限制。也就是在第一次加载时手动设置tableView.firstReload=YES即可


在 2016-12-21 16:05:56，"oragekk" <notifications@github.com> 写道：


当我使用searchBar的时候，跳转的搜索控制器，第一次是没有历史记录的，就会显示占位图，挡住了后边的视图，当有搜索记录的时候，这个问题就没有了。所以我想问可否给一个属性或者方法，指定某些tableview显示或者指定某些tableview不显示
